export type BibleVersion = 'NIV' | 'NKJV' | 'KJV' | 'AMP' | 'MSG'

export const bibleVersionLabels: Record<BibleVersion, string> = {
  NIV: 'NIV',
  NKJV: 'NKJV',
  KJV: 'KJV',
  AMP: 'Amplified',
  MSG: 'The Message',
}

export interface VersionedVerse {
  number: number
  text: string
}

export interface VersionedPassage {
  book: string
  chapter: number
  title: string
  themes: string[]
  versions: Record<BibleVersion, VersionedVerse[]>
}

export const versionedBiblePassages: VersionedPassage[] = [
  {
    book: 'Psalms',
    chapter: 23,
    title: 'The Lord Is My Shepherd',
    themes: ['Peace', 'Comfort', 'Guidance', 'Protection'],
    versions: {
      NIV: [
        { number: 1, text: 'The LORD is my shepherd, I lack nothing.' },
        { number: 2, text: 'He makes me lie down in green pastures, he leads me beside quiet waters,' },
        { number: 3, text: 'he refreshes my soul. He guides me along the right paths for his name\'s sake.' },
        { number: 4, text: 'Even though I walk through the darkest valley, I will fear no evil, for you are with me; your rod and your staff, they comfort me.' },
        { number: 5, text: 'You prepare a table before me in the presence of my enemies. You anoint my head with oil; my cup overflows.' },
        { number: 6, text: 'Surely your goodness and love will follow me all the days of my life, and I will dwell in the house of the LORD forever.' },
      ],
      NKJV: [
        { number: 1, text: 'The LORD is my shepherd; I shall not want.' },
        { number: 2, text: 'He makes me to lie down in green pastures; He leads me beside the still waters.' },
        { number: 3, text: 'He restores my soul; He leads me in the paths of righteousness for His name\'s sake.' },
        { number: 4, text: 'Yea, though I walk through the valley of the shadow of death, I will fear no evil; for You are with me; Your rod and Your staff, they comfort me.' },
        { number: 5, text: 'You prepare a table before me in the presence of my enemies; You anoint my head with oil; my cup runs over.' },
        { number: 6, text: 'Surely goodness and mercy shall follow me all the days of my life; and I will dwell in the house of the LORD forever.' },
      ],
      KJV: [
        { number: 1, text: 'The LORD is my shepherd; I shall not want.' },
        { number: 2, text: 'He maketh me to lie down in green pastures: he leadeth me beside the still waters.' },
        { number: 3, text: 'He restoreth my soul: he leadeth me in the paths of righteousness for his name\'s sake.' },
        { number: 4, text: 'Yea, though I walk through the valley of the shadow of death, I will fear no evil: for thou art with me; thy rod and thy staff they comfort me.' },
        { number: 5, text: 'Thou preparest a table before me in the presence of mine enemies: thou anointest my head with oil; my cup runneth over.' },
        { number: 6, text: 'Surely goodness and mercy shall follow me all the days of my life: and I will dwell in the house of the LORD for ever.' },
      ],
      AMP: [
        { number: 1, text: 'The Lord is my Shepherd [to feed, to guide and to shield me], I shall not want.' },
        { number: 2, text: 'He lets me lie down in green pastures; He leads me beside the still and quiet waters.' },
        { number: 3, text: 'He refreshes and restores my soul (life); He leads me in the paths of righteousness for His name\'s sake.' },
        { number: 4, text: 'Even though I walk through the [sunless] valley of the shadow of death, I fear no evil, for You are with me; Your rod [to protect] and Your staff [to guide], they comfort and console me.' },
        { number: 5, text: 'You prepare a table before me in the presence of my enemies. You have anointed and refreshed my head with oil; my cup overflows.' },
        { number: 6, text: 'Surely goodness and mercy and unfailing love shall follow me all the days of my life, and I shall dwell forever [throughout all my days] in the house and in the presence of the Lord.' },
      ],
      MSG: [
        { number: 1, text: 'God, my shepherd! I don\'t need a thing.' },
        { number: 2, text: 'You have bedded me down in lush meadows, you find me quiet pools to drink from.' },
        { number: 3, text: 'True to your word, you let me catch my breath and send me in the right direction.' },
        { number: 4, text: 'Even when the way goes through Death Valley, I\'m not afraid when you walk at my side. Your trusty shepherd\'s crook makes me feel secure.' },
        { number: 5, text: 'You serve me a six-course dinner right in front of my enemies. You revive my drooping head; my cup brims with blessing.' },
        { number: 6, text: 'Your beauty and love chase after me every day of my life. I\'m back home in the house of God for the rest of my life.' },
      ],
    },
  },

  {
    book: 'Philippians',
    chapter: 4,
    title: 'Rejoice in the Lord Always',
    themes: ['Anxiety', 'Peace', 'Strength', 'Contentment'],
    versions: {
      NIV: [
        { number: 4, text: 'Rejoice in the Lord always. I will say it again: Rejoice!' },
        { number: 5, text: 'Let your gentleness be evident to all. The Lord is near.' },
        { number: 6, text: 'Do not be anxious about anything, but in every situation, by prayer and petition, with thanksgiving, present your requests to God.' },
        { number: 7, text: 'And the peace of God, which transcends all understanding, will guard your hearts and your minds in Christ Jesus.' },
        { number: 8, text: 'Finally, brothers and sisters, whatever is true, whatever is noble, whatever is right, whatever is pure, whatever is lovely, whatever is admirable—if anything is excellent or praiseworthy—think about such things.' },
        { number: 13, text: 'I can do all this through him who gives me strength.' },
      ],
      NKJV: [
        { number: 4, text: 'Rejoice in the Lord always. Again I will say, rejoice!' },
        { number: 5, text: 'Let your gentleness be known to all men. The Lord is at hand.' },
        { number: 6, text: 'Be anxious for nothing, but in everything by prayer and supplication, with thanksgiving, let your requests be made known to God;' },
        { number: 7, text: 'and the peace of God, which surpasses all understanding, will guard your hearts and minds through Christ Jesus.' },
        { number: 8, text: 'Finally, brethren, whatever things are true, whatever things are noble, whatever things are just, whatever things are pure, whatever things are lovely, whatever things are of good report, if there is any virtue and if there is anything praiseworthy—meditate on these things.' },
        { number: 13, text: 'I can do all things through Christ who strengthens me.' },
      ],
      KJV: [
        { number: 4, text: 'Rejoice in the Lord alway: and again I say, Rejoice.' },
        { number: 5, text: 'Let your moderation be known unto all men. The Lord is at hand.' },
        { number: 6, text: 'Be careful for nothing; but in every thing by prayer and supplication with thanksgiving let your requests be made known unto God.' },
        { number: 7, text: 'And the peace of God, which passeth all understanding, shall keep your hearts and minds through Christ Jesus.' },
        { number: 8, text: 'Finally, brethren, whatsoever things are true, whatsoever things are honest, whatsoever things are just, whatsoever things are pure, whatsoever things are lovely, whatsoever things are of good report; if there be any virtue, and if there be any praise, think on these things.' },
        { number: 13, text: 'I can do all things through Christ which strengtheneth me.' },
      ],
      AMP: [
        { number: 4, text: 'Rejoice in the Lord always [delight, take pleasure in Him]; again I will say, rejoice!' },
        { number: 5, text: 'Let your gentle spirit [your graciousness, unselfishness, mercy, tolerance, and patience] be known to all people. The Lord is near.' },
        { number: 6, text: 'Do not be anxious or worried about anything, but in everything [every circumstance and situation] by prayer and petition with thanksgiving, continue to make your [specific] requests known to God.' },
        { number: 7, text: 'And the peace of God [that peace which reassures the heart, that peace which transcends all understanding, that peace which] stands guard over your hearts and your minds in Christ Jesus [is yours].' },
        { number: 8, text: 'Finally, believers, whatever is true, whatever is honorable and worthy of respect, whatever is right and confirmed by God\'s word, whatever is pure and wholesome, whatever is lovely and brings peace, whatever is admirable and of good repute; if there is any excellence, if there is anything worthy of praise, think continually on these things [center your mind on them, and implant them in your heart].' },
        { number: 13, text: 'I can do all things [which He has called me to do] through Him who strengthens and empowers me [to fulfill His purpose—I am self-sufficient in Christ\'s sufficiency; I am ready for anything and equal to anything through Him who infuses me with inner strength and confident peace].' },
      ],
      MSG: [
        { number: 4, text: 'Celebrate God all day, every day. I mean, revel in him!' },
        { number: 5, text: 'Make it as clear as you can to all you meet that you\'re on their side, working with them and not against them. Help them see that the Master is about to arrive. He could show up any minute!' },
        { number: 6, text: 'Don\'t fret or worry. Instead of worrying, pray. Let petitions and praises shape your worries into prayers, letting God know your concerns.' },
        { number: 7, text: 'Before you know it, a sense of God\'s wholeness, everything coming together for good, will come and settle you down. It\'s wonderful what happens when Christ displaces worry at the center of your life.' },
        { number: 8, text: 'Summing it all up, friends, I\'d say you\'ll do best by filling your minds and meditating on things true, noble, reputable, authentic, compelling, gracious—the best, not the worst; the beautiful, not the ugly; things to praise, not things to curse.' },
        { number: 13, text: 'Whatever I have, wherever I am, I can make it through anything in the One who makes me who I am.' },
      ],
    },
  },

  {
    book: 'John',
    chapter: 8,
    title: 'The Truth Will Set You Free',
    themes: ['Freedom', 'Truth', 'Victory', 'Identity'],
    versions: {
      NIV: [
        { number: 31, text: 'To the Jews who had believed him, Jesus said, "If you hold to my teaching, you are really my disciples."' },
        { number: 32, text: '"Then you will know the truth, and the truth will set you free."' },
        { number: 34, text: 'Jesus replied, "Very truly I tell you, everyone who sins is a slave to sin."' },
        { number: 35, text: '"Now a slave has no permanent place in the family, but a son belongs to it forever."' },
        { number: 36, text: '"So if the Son sets you free, you will be free indeed."' },
      ],
      NKJV: [
        { number: 31, text: 'Then Jesus said to those Jews who believed Him, "If you abide in My word, you are My disciples indeed."' },
        { number: 32, text: '"And you shall know the truth, and the truth shall make you free."' },
        { number: 34, text: 'Jesus answered them, "Most assuredly, I say to you, whoever commits sin is a slave of sin."' },
        { number: 35, text: '"And a slave does not abide in the house forever, but a son abides forever."' },
        { number: 36, text: '"Therefore if the Son makes you free, you shall be free indeed."' },
      ],
      KJV: [
        { number: 31, text: 'Then said Jesus to those Jews which believed on him, If ye continue in my word, then are ye my disciples indeed;' },
        { number: 32, text: 'And ye shall know the truth, and the truth shall make you free.' },
        { number: 34, text: 'Jesus answered them, Verily, verily, I say unto you, Whosoever committeth sin is the servant of sin.' },
        { number: 35, text: 'And the servant abideth not in the house for ever: but the Son abideth ever.' },
        { number: 36, text: 'If the Son therefore shall make you free, ye shall be free indeed.' },
      ],
      AMP: [
        { number: 31, text: 'So Jesus was saying to the Jews who had believed Him, "If you abide in My word [continually obeying My teachings and living in accordance with them], then you are truly My disciples."' },
        { number: 32, text: '"And you will know the truth [regarding salvation], and the truth will set you free [from the penalty of sin]."' },
        { number: 34, text: 'Jesus answered, "I assure you and most solemnly say to you, everyone who practices sin habitually is a slave of sin."' },
        { number: 35, text: '"Now the slave does not remain in a household forever; the son [of the master] does remain forever."' },
        { number: 36, text: '"So if the Son makes you free, you will be free indeed."' },
      ],
      MSG: [
        { number: 31, text: 'Then Jesus turned to the Jews who had claimed to believe in him. "If you stick with this, living out what I tell you, you are my disciples for sure."' },
        { number: 32, text: '"Then you will experience for yourselves the truth, and the truth will free you."' },
        { number: 34, text: 'Jesus said, "I tell you most solemnly that anyone who chooses a life of sin is trapped in a dead-end life and is, in fact, a slave."' },
        { number: 35, text: '"A slave is a transient, who can\'t come and go at will. The Son, though, has an established position, the run of the house."' },
        { number: 36, text: '"So if the Son sets you free, you are free through and through."' },
      ],
    },
  },

  {
    book: 'Romans',
    chapter: 8,
    title: 'Life Through the Spirit',
    themes: ['Victory', 'Freedom', 'Peace', 'Love', 'Conquerors'],
    versions: {
      NIV: [
        { number: 1, text: 'Therefore, there is now no condemnation for those who are in Christ Jesus,' },
        { number: 2, text: 'because through Christ Jesus the law of the Spirit who gives life has set you free from the law of sin and death.' },
        { number: 5, text: 'Those who live according to the flesh have their minds set on what the flesh desires; but those who live in accordance with the Spirit have their minds set on what the Spirit desires.' },
        { number: 6, text: 'The mind governed by the flesh is death, but the mind governed by the Spirit is life and peace.' },
        { number: 37, text: 'No, in all these things we are more than conquerors through him who loved us.' },
        { number: 38, text: 'For I am convinced that neither death nor life, neither angels nor demons, neither the present nor the future, nor any powers,' },
        { number: 39, text: 'neither height nor depth, nor anything else in all creation, will be able to separate us from the love of God that is in Christ Jesus our Lord.' },
      ],
      NKJV: [
        { number: 1, text: 'There is therefore now no condemnation to those who are in Christ Jesus, who do not walk according to the flesh, but according to the Spirit.' },
        { number: 2, text: 'For the law of the Spirit of life in Christ Jesus has made me free from the law of sin and death.' },
        { number: 5, text: 'For those who live according to the flesh set their minds on the things of the flesh, but those who live according to the Spirit, the things of the Spirit.' },
        { number: 6, text: 'For to be carnally minded is death, but to be spiritually minded is life and peace.' },
        { number: 37, text: 'Yet in all these things we are more than conquerors through Him who loved us.' },
        { number: 38, text: 'For I am persuaded that neither death nor life, nor angels nor principalities nor powers, nor things present nor things to come,' },
        { number: 39, text: 'nor height nor depth, nor any other created thing, shall be able to separate us from the love of God which is in Christ Jesus our Lord.' },
      ],
      KJV: [
        { number: 1, text: 'There is therefore now no condemnation to them which are in Christ Jesus, who walk not after the flesh, but after the Spirit.' },
        { number: 2, text: 'For the law of the Spirit of life in Christ Jesus hath made me free from the law of sin and death.' },
        { number: 5, text: 'For they that are after the flesh do mind the things of the flesh; but they that are after the Spirit the things of the Spirit.' },
        { number: 6, text: 'For to be carnally minded is death; but to be spiritually minded is life and peace.' },
        { number: 37, text: 'Nay, in all these things we are more than conquerors through him that loved us.' },
        { number: 38, text: 'For I am persuaded, that neither death, nor life, nor angels, nor principalities, nor powers, nor things present, nor things to come,' },
        { number: 39, text: 'Nor height, nor depth, nor any other creature, shall be able to separate us from the love of God, which is in Christ Jesus our Lord.' },
      ],
      AMP: [
        { number: 1, text: 'Therefore there is now no condemnation [no guilty verdict, no punishment] for those who are in Christ Jesus [who believe in Him as personal Lord and Savior].' },
        { number: 2, text: 'For the law of the Spirit of life [which is] in Christ Jesus [the law of our new being] has set you free from the law of sin and of death.' },
        { number: 5, text: 'For those who are living according to the flesh set their minds on the things of the flesh [which gratify the body], but those who are living according to the Spirit, [set their minds on] the things of the Spirit [His will and purpose].' },
        { number: 6, text: 'Now the mind of the flesh is death [both now and forever—because it pursues sin]; but the mind of the Spirit is life and peace [the spiritual well-being that comes from walking with God—both now and forever].' },
        { number: 37, text: 'Yet in all these things we are more than conquerors and gain an overwhelming victory through Him who loved us [so much that He died for us].' },
        { number: 38, text: 'For I am convinced [and continue to be convinced—beyond any doubt] that neither death, nor life, nor angels, nor principalities, nor things present and threatening, nor things to come, nor powers,' },
        { number: 39, text: 'nor height, nor depth, nor any other created thing, will be able to separate us from the [unlimited] love of God, which is in Christ Jesus our Lord.' },
      ],
      MSG: [
        { number: 1, text: 'With the arrival of Jesus, the Messiah, that fateful dilemma is resolved. Those who enter into Christ\'s being-here-for-us no longer have to live under a continuous, low-lying black cloud.' },
        { number: 2, text: 'A new power is in operation. The Spirit of life in Christ, like a strong wind, has magnificently cleared the air, freeing you from a fated lifetime of brutal tyranny at the hands of sin and death.' },
        { number: 5, text: 'Those who think they can do it on their own end up obsessed with measuring their own moral muscle but never get around to exercising it in real life. Those who trust God\'s action in them find that God\'s Spirit is in them—living and breathing God!' },
        { number: 6, text: 'Obsession with self in these matters is a dead end; attention to God leads us out into the open, into a spacious, free life.' },
        { number: 37, text: 'None of this fazes us because Jesus loves us.' },
        { number: 38, text: 'I\'m absolutely convinced that nothing—nothing living or dead, angelic or demonic, today or tomorrow, high or low,' },
        { number: 39, text: 'thinkable or unthinkable—absolutely nothing can get between us and God\'s love because of the way that Jesus our Master has embraced us.' },
      ],
    },
  },

  {
    book: 'James',
    chapter: 1,
    title: 'Trials and Temptations',
    themes: ['Temptation', 'Trials', 'Wisdom', 'Faith', 'Perseverance'],
    versions: {
      NIV: [
        { number: 2, text: 'Consider it pure joy, my brothers and sisters, whenever you face trials of many kinds,' },
        { number: 3, text: 'because you know that the testing of your faith produces perseverance.' },
        { number: 4, text: 'Let perseverance finish its work so that you may be mature and complete, not lacking anything.' },
        { number: 5, text: 'If any of you lacks wisdom, you should ask God, who gives generously to all without finding fault, and it will be given to you.' },
        { number: 12, text: 'Blessed is the one who perseveres under trial because, having stood the test, that person will receive the crown of life that the Lord has promised to those who love him.' },
        { number: 13, text: 'When tempted, no one should say, "God is tempting me." For God cannot be tempted by evil, nor does he tempt anyone;' },
        { number: 14, text: 'but each person is tempted when they are dragged away by their own evil desire and enticed.' },
        { number: 15, text: 'Then, after desire has conceived, it gives birth to sin; and sin, when it is full-grown, gives birth to death.' },
      ],
      NKJV: [
        { number: 2, text: 'My brethren, count it all joy when you fall into various trials,' },
        { number: 3, text: 'knowing that the testing of your faith produces patience.' },
        { number: 4, text: 'But let patience have its perfect work, that you may be perfect and complete, lacking nothing.' },
        { number: 5, text: 'If any of you lacks wisdom, let him ask of God, who gives to all liberally and without reproach, and it will be given to him.' },
        { number: 12, text: 'Blessed is the man who endures temptation; for when he has been approved, he will receive the crown of life which the Lord has promised to those who love Him.' },
        { number: 13, text: 'Let no one say when he is tempted, "I am tempted by God"; for God cannot be tempted by evil, nor does He Himself tempt anyone.' },
        { number: 14, text: 'But each one is tempted when he is drawn away by his own desires and enticed.' },
        { number: 15, text: 'Then, when desire has conceived, it gives birth to sin; and sin, when it is full-grown, brings forth death.' },
      ],
      KJV: [
        { number: 2, text: 'My brethren, count it all joy when ye fall into divers temptations;' },
        { number: 3, text: 'Knowing this, that the trying of your faith worketh patience.' },
        { number: 4, text: 'But let patience have her perfect work, that ye may be perfect and entire, wanting nothing.' },
        { number: 5, text: 'If any of you lack wisdom, let him ask of God, that giveth to all men liberally, and upbraideth not; and it shall be given him.' },
        { number: 12, text: 'Blessed is the man that endureth temptation: for when he is tried, he shall receive the crown of life, which the Lord hath promised to them that love him.' },
        { number: 13, text: 'Let no man say when he is tempted, I am tempted of God: for God cannot be tempted with evil, neither tempteth he any man:' },
        { number: 14, text: 'But every man is tempted, when he is drawn away of his own lust, and enticed.' },
        { number: 15, text: 'Then when lust hath conceived, it bringeth forth sin: and sin, when it is finished, bringeth forth death.' },
      ],
      AMP: [
        { number: 2, text: 'Consider it nothing but joy, my brothers and sisters, whenever you fall into various trials.' },
        { number: 3, text: 'Be assured that the testing of your faith [through experience] produces endurance [leading to spiritual maturity, and inner peace].' },
        { number: 4, text: 'And let endurance have its perfect result and do a thorough work, so that you may be perfect and completely developed [in your faith], lacking in nothing.' },
        { number: 5, text: 'If any of you lacks wisdom [to guide him through a decision or circumstance], he is to ask of [our benevolent] God, who gives to everyone generously and without rebuke or blame, and it will be given to him.' },
        { number: 12, text: 'Blessed [happy, spiritually prosperous, favored by God] is the man who is steadfast under trial and perseveres when tempted; for when he has passed the test and been approved, he will receive the [victor\'s] crown of life which the Lord has promised to those who love Him.' },
        { number: 13, text: 'Let no one say when he is tempted, "I am being tempted by God" [for temptation does not originate from God, but from our own flaws]; for God cannot be tempted by [what is] evil, and He Himself tempts no one.' },
        { number: 14, text: 'But each one is tempted when he is dragged away, enticed and baited [to commit sin] by his own [worldly] desire (lust, passions).' },
        { number: 15, text: 'Then when the illicit desire has conceived, it gives birth to sin; and when sin has run its course, it gives birth to death.' },
      ],
      MSG: [
        { number: 2, text: 'Consider it a sheer gift, friends, when tests and challenges come at you from all sides.' },
        { number: 3, text: 'You know that under pressure, your faith-life is forced into the open and shows its true colors.' },
        { number: 4, text: 'So don\'t try to get out of anything prematurely. Let it do its work so you become mature and well-developed, not deficient in any way.' },
        { number: 5, text: 'If you don\'t know what you\'re doing, pray to the Father. He loves to help. You\'ll get his help, and won\'t be condescended to when you ask for it.' },
        { number: 12, text: 'Anyone who meets a testing challenge head-on and manages to stick it out is mighty fortunate. For such persons loyally in love with God, the reward is life and more life.' },
        { number: 13, text: 'Don\'t let anyone under pressure to give in to evil say, "God is trying to trip me up." God is impervious to evil, and puts evil in no one\'s way.' },
        { number: 14, text: 'The temptation to give in to evil comes from us and only us. We have no one to blame but the leering, seducing flare-up of our own lust.' },
        { number: 15, text: 'Lust gets pregnant, and has a baby: sin! Sin grows up to adulthood, and becomes a real killer.' },
      ],
    },
  },

  {
    book: '2 Corinthians',
    chapter: 5,
    title: 'A New Creation',
    themes: ['New Creation', 'Reconciliation', 'Freedom', 'Identity'],
    versions: {
      NIV: [
        { number: 17, text: 'Therefore, if anyone is in Christ, the new creation has come: The old has gone, the new is here!' },
        { number: 18, text: 'All this is from God, who reconciled us to himself through Christ and gave us the ministry of reconciliation:' },
        { number: 19, text: 'that God was reconciling the world to himself in Christ, not counting people\'s sins against them. And he has committed to us the message of reconciliation.' },
        { number: 20, text: 'We are therefore Christ\'s ambassadors, as though God were making his appeal through us. We implore you on Christ\'s behalf: Be reconciled to God.' },
        { number: 21, text: 'God made him who had no sin to be sin for us, so that in him we might become the righteousness of God.' },
      ],
      NKJV: [
        { number: 17, text: 'Therefore, if anyone is in Christ, he is a new creation; old things have passed away; behold, all things have become new.' },
        { number: 18, text: 'Now all things are of God, who has reconciled us to Himself through Jesus Christ, and has given us the ministry of reconciliation,' },
        { number: 19, text: 'that is, that God was in Christ reconciling the world to Himself, not imputing their trespasses to them, and has committed to us the word of reconciliation.' },
        { number: 20, text: 'Now then, we are ambassadors for Christ, as though God were pleading through us: we implore you on Christ\'s behalf, be reconciled to God.' },
        { number: 21, text: 'For He made Him who knew no sin to be sin for us, that we might become the righteousness of God in Him.' },
      ],
      KJV: [
        { number: 17, text: 'Therefore if any man be in Christ, he is a new creature: old things are passed away; behold, all things are become new.' },
        { number: 18, text: 'And all things are of God, who hath reconciled us to himself by Jesus Christ, and hath given to us the ministry of reconciliation;' },
        { number: 19, text: 'To wit, that God was in Christ, reconciling the world unto himself, not imputing their trespasses unto them; and hath committed unto us the word of reconciliation.' },
        { number: 20, text: 'Now then we are ambassadors for Christ, as though God did beseech you by us: we pray you in Christ\'s stead, be ye reconciled to God.' },
        { number: 21, text: 'For he hath made him to be sin for us, who knew no sin; that we might be made the righteousness of God in him.' },
      ],
      AMP: [
        { number: 17, text: 'Therefore if anyone is in Christ [that is, grafted in, joined to Him by faith in Him as Savior], he is a new creature [reborn and renewed by the Holy Spirit]; the old things [the previous moral and spiritual condition] have passed away. Behold, new things have come [because spiritual awakening brings a new life].' },
        { number: 18, text: 'But all these things are from God, who reconciled us to Himself through Christ [making us acceptable to Him] and gave us the ministry of reconciliation [so that by our example we might bring others to Him],' },
        { number: 19, text: 'that is, that God was in Christ reconciling the world to Himself, not counting people\'s sins against them [but canceling them]. And He has committed to us the message of reconciliation [that is, restoration to favor with God].' },
        { number: 20, text: 'So we are ambassadors for Christ, as though God were making His appeal through us; we [as Christ\'s representatives] plead with you on behalf of Christ to be reconciled to God.' },
        { number: 21, text: 'He made Christ who knew no sin to [judicially] be sin on our behalf, so that in Him we would become the righteousness of God [that is, we would be made acceptable to Him and placed in a right relationship with Him by His gracious lovingkindness].' },
      ],
      MSG: [
        { number: 17, text: 'Now we look inside, and what we see is that anyone united with the Messiah gets a fresh start, is created new. The old life is gone; a new life burgeons! Look at it!' },
        { number: 18, text: 'All this comes from the God who settled the relationship between us and him, and then called us to settle our relationships with each other.' },
        { number: 19, text: 'God put the world square with himself through the Messiah, giving the world a fresh start by offering forgiveness of sins. God has given us the task of telling everyone what he is doing.' },
        { number: 20, text: 'We\'re Christ\'s representatives. God uses us to persuade men and women to drop their differences and enter into God\'s work of making things right between them. We\'re speaking for Christ himself now: Become friends with God; he\'s already a friend with you.' },
        { number: 21, text: 'How? you ask. In Christ. God put the wrong on him who never did anything wrong, so we could be put right with God.' },
      ],
    },
  },

  {
    book: '1 Corinthians',
    chapter: 10,
    title: 'Warnings and the Way of Escape',
    themes: ['Temptation', 'Escape', 'Faithfulness', 'Freedom'],
    versions: {
      NIV: [
        { number: 12, text: 'So, if you think you are standing firm, be careful that you don\'t fall!' },
        { number: 13, text: 'No temptation has overtaken you except what is common to mankind. And God is faithful; he will not let you be tempted beyond what you can bear. But when you are tempted, he will also provide a way out so that you can endure it.' },
        { number: 23, text: '"I have the right to do anything," you say—but not everything is beneficial. "I have the right to do anything"—but not everything is constructive.' },
        { number: 31, text: 'So whether you eat or drink or whatever you do, do it all for the glory of God.' },
      ],
      NKJV: [
        { number: 12, text: 'Therefore let him who thinks he stands take heed lest he fall.' },
        { number: 13, text: 'No temptation has overtaken you except such as is common to man; but God is faithful, who will not allow you to be tempted beyond what you are able, but with the temptation will also make the way of escape, that you may be able to bear it.' },
        { number: 23, text: 'All things are lawful for me, but not all things are helpful; all things are lawful for me, but not all things edify.' },
        { number: 31, text: 'Therefore, whether you eat or drink, or whatever you do, do all to the glory of God.' },
      ],
      KJV: [
        { number: 12, text: 'Wherefore let him that thinketh he standeth take heed lest he fall.' },
        { number: 13, text: 'There hath no temptation taken you but such as is common to man: but God is faithful, who will not suffer you to be tempted above that ye are able; but will with the temptation also make a way to escape, that ye may be able to bear it.' },
        { number: 23, text: 'All things are lawful for me, but all things are not expedient: all things are lawful for me, but all things edify not.' },
        { number: 31, text: 'Whether therefore ye eat, or drink, or whatsoever ye do, do all to the glory of God.' },
      ],
      AMP: [
        { number: 12, text: 'Therefore let the one who thinks he stands firm [immune to temptation, being overconfident and self-righteous], take care that he does not fall [into sin and condemnation].' },
        { number: 13, text: 'No temptation [regardless of its source] has overtaken or enticed you that is not common to human experience [nor is any temptation unusual or beyond human resistance]; but God is faithful [to His word—He is compassionate and trustworthy], and He will not let you be tempted beyond your ability [to resist], but along with the temptation He [has in the past and is now and] will [always] provide the way out as well, so that you will be able to endure it [without yielding, and will overcome temptation with joy].' },
        { number: 23, text: 'All things are lawful [that is, morally legitimate, permissible], but not all things are beneficial or advantageous. All things are lawful, but not all things are constructive [to character] and edifying [to spiritual life].' },
        { number: 31, text: 'So then, whether you eat or drink or whatever you do, do all to the glory of [our great] God.' },
      ],
      MSG: [
        { number: 12, text: 'Don\'t be so naive and self-confident. You\'re not exempt. You could fall flat on your face as easily as anyone else. Forget about self-confidence; it\'s useless. Cultivate God-confidence.' },
        { number: 13, text: 'No test or temptation that comes your way is beyond the course of what others have had to face. All you need to remember is that God will never let you down; he\'ll never let you be pushed past your limit; he\'ll always be there to help you come through it.' },
        { number: 23, text: 'Looking at it one way, you could say, "Anything goes. Because of God\'s immense generosity and grace, we don\'t have to dissect and scrutinize every action to see if it will pass muster." But the point is not to just get by. We want to live well, and the test is: Will this do good for the person I\'m with?' },
        { number: 31, text: 'So eat your meals heartily, not worrying about what others say about you—you\'re eating to God\'s glory, after all, not to please them.' },
      ],
    },
  },

  {
    book: 'Proverbs',
    chapter: 13,
    title: 'Trust The Process — Hope, Wisdom & God\'s Timing',
    themes: ['Faith', 'Perseverance', 'Wisdom', 'Hope', 'Patience'],
    versions: {
      NIV: [
        { number: 12, text: 'Hope deferred makes the heart sick, but a longing fulfilled is a tree of life.' },
        { number: 13, text: 'Whoever scorns instruction will pay for it, but whoever respects a command is rewarded.' },
        { number: 14, text: 'The teaching of the wise is a fountain of life, turning a person from the snares of death.' },
        { number: 15, text: 'Good judgment wins favor, but the way of the unfaithful leads to their destruction.' },
        { number: 16, text: 'All who are prudent act with knowledge, but fools expose their folly.' },
        { number: 17, text: 'A wicked messenger falls into trouble, but a trustworthy envoy brings healing.' },
        { number: 18, text: 'Whoever disregards discipline comes to poverty and shame, but whoever heeds correction is honored.' },
        { number: 19, text: 'A longing fulfilled is sweet to the soul, but fools detest turning from evil.' },
        { number: 20, text: 'Walk with the wise and become wise, for a companion of fools suffers harm.' },
        { number: 21, text: 'Trouble pursues the sinner, but the righteous are rewarded with good things.' },
        { number: 22, text: 'A good person leaves an inheritance for their children\'s children, but a sinner\'s wealth is stored up for the righteous.' },
        { number: 23, text: 'An unplowed field produces food for the poor, but injustice sweeps it away.' },
      ],
      NKJV: [
        { number: 12, text: 'Hope deferred makes the heart sick, but when the desire comes, it is a tree of life.' },
        { number: 13, text: 'He who despises the word will be destroyed, but he who fears the commandment will be rewarded.' },
        { number: 14, text: 'The law of the wise is a fountain of life, to turn one away from the snares of death.' },
        { number: 15, text: 'Good understanding gains favor, but the way of the unfaithful is hard.' },
        { number: 16, text: 'Every prudent man acts with knowledge, but a fool lays open his folly.' },
        { number: 17, text: 'A wicked messenger falls into trouble, but a faithful ambassador brings health.' },
        { number: 18, text: 'Poverty and shame will come to him who disdains correction, but he who regards a rebuke will be honored.' },
        { number: 19, text: 'A desire accomplished is sweet to the soul, but it is an abomination to fools to depart from evil.' },
        { number: 20, text: 'He who walks with wise men will be wise, but the companion of fools will be destroyed.' },
        { number: 21, text: 'Evil pursues sinners, but to the righteous, good shall be repaid.' },
        { number: 22, text: 'A good man leaves an inheritance to his children\'s children, but the wealth of the sinner is stored up for the righteous.' },
        { number: 23, text: 'Much food is in the fallow ground of the poor, and for lack of justice there is waste.' },
      ],
      KJV: [
        { number: 12, text: 'Hope deferred maketh the heart sick: but when the desire cometh, it is a tree of life.' },
        { number: 13, text: 'Whoso despiseth the word shall be destroyed: but he that feareth the commandment shall be rewarded.' },
        { number: 14, text: 'The law of the wise is a fountain of life, to depart from the snares of death.' },
        { number: 15, text: 'Good understanding giveth favour: but the way of transgressors is hard.' },
        { number: 16, text: 'Every prudent man dealeth with knowledge: but a fool layeth open his folly.' },
        { number: 17, text: 'A wicked messenger falleth into mischief: but a faithful ambassador is health.' },
        { number: 18, text: 'Poverty and shame shall be to him that refuseth instruction: but he that regardeth reproof shall be honoured.' },
        { number: 19, text: 'The desire accomplished is sweet to the soul: but it is abomination to fools to depart from evil.' },
        { number: 20, text: 'He that walketh with wise men shall be wise: but a companion of fools shall be destroyed.' },
        { number: 21, text: 'Evil pursueth sinners: but to the righteous good shall be repayed.' },
        { number: 22, text: 'A good man leaveth an inheritance to his children\'s children: and the wealth of the sinner is laid up for the just.' },
        { number: 23, text: 'Much food is in the tillage of the poor: but there is that is destroyed for want of judgment.' },
      ],
      AMP: [
        { number: 12, text: 'Hope deferred makes the heart sick, but desire fulfilled is a tree of life.' },
        { number: 13, text: 'Whoever despises the word and counsel [of God] brings destruction upon himself, but he who [reverently] fears and respects the commandment [of God] will be rewarded.' },
        { number: 14, text: 'The teaching of the wise is a fountain of life, to turn aside from the snares of death.' },
        { number: 15, text: 'Good understanding and godly wisdom give favor, but the way of the treacherous is hard [like barren, dry ground].' },
        { number: 16, text: 'Every prudent and self-disciplined man acts with knowledge, but a [closed-minded] fool [who refuses to learn] displays and exposes his foolishness.' },
        { number: 17, text: 'A wicked messenger falls into adversity, but a faithful and trustworthy envoy brings healing.' },
        { number: 18, text: 'Poverty and shame come to him who ignores instruction and discipline, but he who learns from rebuke and is corrected will be honored.' },
        { number: 19, text: 'Desire realized is sweet to the soul; it is an abomination [an absolute disgust] to fools to turn away from evil and sin.' },
        { number: 20, text: 'He who walks [as a companion] with wise men will be wise, but the companions of [conceited, dull-witted] fools [who ridicule wisdom] will experience harm.' },
        { number: 21, text: 'Adversity pursues sinners [as a punishment], but the righteous will be rewarded with prosperity and good things.' },
        { number: 22, text: 'A good man leaves an inheritance [of moral stability and goodness] to his children\'s children, and the wealth of the sinner is stored up for [the hands of] the righteous.' },
        { number: 23, text: 'Abundant food is in the fallow ground of the poor [which awaits the time of cultivation], but it is swept away by injustice.' },
      ],
      MSG: [
        { number: 12, text: 'Unrelenting disappointment leaves you heartsick, but a sudden good break can turn life around.' },
        { number: 13, text: 'Ignore the Word and suffer; honor God\'s commands and grow rich.' },
        { number: 14, text: 'The teaching of the wise is a spring of water to drink; the guidance of fools is dangerous water.' },
        { number: 15, text: 'Sound thinking makes for gracious living, but liars walk a rough road.' },
        { number: 16, text: 'Prudent people don\'t flaunt their knowledge; talkative fools broadcast their silliness.' },
        { number: 17, text: 'Irresponsible talk makes a real mess of things; a reliable reporter is a healing presence.' },
        { number: 18, text: 'Refuse discipline and end up homeless; embrace correction and live an honored life.' },
        { number: 19, text: 'Souls who follow their hearts thrive; fools bent on evil despise matters of soul.' },
        { number: 20, text: 'Become wise by walking with the wise; hang out with fools and watch your life fall apart.' },
        { number: 21, text: 'Catastrophe is linked to sin; goodness is linked to God-blessed living.' },
        { number: 22, text: 'A good life gets passed on to the grandchildren; ill-gotten wealth ends up with good people.' },
        { number: 23, text: 'Banks foreclose on the farms of the poor, or else the poor lose their shirts to crooked lawyers.' },
      ],
    },
  },
]
